### ISSUE TITLE
Request: Combine interactions

### ISSUE THREAD

**Issue by Fanvaron** [samuelOsborne/Lottie-interactive#15]
Hi,
first of all thanks for making this, I'm new to lottie, and besides the fact that the naming overlap of interactive and interactivity had me confused for a solid 2 hours, this seems like a great way to get lottie animations into the page quickly without needing lots of code for every single image.

My Request now is if it is possible (or would be possible to add) to use more than one interaction at once.
In my case I would like to have the play-on-show and click both. 
So that it plays once automatically but if the visitor is interested they can play it again by clicking.

Best Regards
Marvin

**Comment by samuelOsborne** [comment]
Hey Marvin,

That's a great idea, I'll put it in for the next release. If you need it urgently let me know and I'll see if there's a work-around in the time being ?

Cheers,

Sam

**Comment by Fanvaron** [comment]
Hi Sam,
Thanks for the quick reply.
No its not that urgend.
I'm slowly working my way down the page and all the images I'm working on right now are in view from the start, so I'm just using an autoplay + delay for those.
And since I'm still rather slow in getting the lotties together it will probably be a few weeks since I actually need that function.

Best,
Marvin

**Comment by samuelOsborne** [comment]
Hi @Fanvaron ,

With the released v1.3.0 you can now use the 'show-and-click' interaction to play an animation on show, and then again when clicking. Thanks for this request, I've also added:

## show-and-freeze-click

Plays the animation when it appears on screen and is then interactive with the freeze-click interaction!

## show-and-morph

Plays the animation when it appears on screen and is then interactive with the morphing interaction!

## show-and-morph-lock

Plays the animation when it appears on screen and is then interactive with the morph-lock interaction!

## show-and-switch

Plays the animation when it appears on screen and is then interactive with the switch interaction!
